### ISSUE TITLE
Where is the color ?

### ISSUE THREAD

**Issue by Gluups** [emvaized/tst-colorize-tabs#1]
Hello,
I am in Firefox 100.0 on Windows 10.
OK I reinstalled Tree Style Tab to update it, installed TST-Colorize-Tabs, and found "Color" in the contextual menu of each tab.
May I know where the color is supposed to appear ?

Previously I saw that TST-Colored-Tabs had set colors for all tabs (in Tree Style Tab only), but I should like to colorize just one, so I uninstalled it and tried TST-Colorize-Tabs. But I do not see the color except in the contextual menu.

I presume the conflicts are the same for both extensions ?

**Comment by emvaized** [comment]
Hi! There's currently an issue which I'm planning to investigate soon, which results in CSS styles are not being applied by the extension after browser start. As a workaround until I'll find the solution, try to disable and enable the extension – this way all the colors should be applied correctly until next browser restart.

**Comment by Gluups** [comment]
Hello,

Oh, I see, thank you.
Must I do that each time I want to apply a colour to a tab ?

I try that tomorrow, although I am less available than planned since 
yesterday night.

______________________________________
On 07th May 2022 à 17:50 UTC + 2, Max wrote :

**Comment by emvaized** [comment]
No, only need to do it once after browser start

**Comment by Gluups** [comment]
OK, I did that, the colour appeared.

But something strange happens. I am on tab n+1, I click on tab n in Tree 
Style Tab, and I get tab n-1 selected.
And same sort of thing about the colour.

This would deserve some more structured tests, but I am not really 
available enough to do it properly, sorry.

________________________________________
On 07th May 2022 at 18:31 UTC + 2, Max wrote :

**Comment by emvaized** [comment]
I never noticed such a behavior in my case. Maybe it comes from another addon? Because this one shouldn't anyhow affect which tab is selected.

**Comment by Gluups** [comment]
I had the impression that one tab did not want to be selected.
I try and be more precise as soon as I can.


On 07th May 2022 at 19:24 UTC + 2, Max wrote :

**Comment by emvaized** [comment]
I think this issue should be fixed now in version 1.0.1 – no browser restart is required anymore.

**Comment by Gluups** [comment]
OK thank you.

I did not get it first, for I had forgotten that the colour is only 
possible in Tree Style Tab.

By default, the tabs are colored #FFC999, and the colour given by the 
extension is mixed with it.
If I say Blue, I obtain a sort of violet.

I imagine I should put white as a default colour with userChrome.css to 
obtain the colour selected in the extension.

The problem I signalled to select a tab is rather a problem with Tree 
Style Tab.

So, problem solved, thank you.

________________________________________
On 11th May 2022 at 22:33 UTC + 2, Max wrote :
