### ISSUE TITLE
All color tabs lose after browser restart

### ISSUE THREAD

**Issue by info999** [emvaized/tst-colorize-tabs#2]
It would be great to restore color tabs after browser restart.
Or may be it is only my issue?

**Comment by emvaized** [comment]
Hm, colors get restored on browser restart just fine for me

**Comment by info999** [comment]
Checked on other simple Firefox profile.
It does work.
I think I have to find incompatibility with other addons.

**Comment by kings2u** [comment]
Sometimes I find that the colors don’t show up after a browser restart even though when I right click on a tab and go to the Color menu, the appropriate color is selected/greyed out. Refreshing the tab doesn’t reapply the color; instead I have to change the tab to a different color, then change the color back to what it was supposed to be.

**Comment by emvaized** [comment]
@kings2u 
Refreshing the tab shouldn't help, as colors get applied only in two cases: on extension load up, and when you apply a new color through the context menu. Let's continue discussing your issue in the related ticket.
