### ISSUE TITLE
Sometimes actual tree color doesn’t reflect selected tree color

### ISSUE THREAD

**Issue by kings2u** [emvaized/tst-colorize-tabs#5]
This can be seen in this screenshot, where the tab is actually green but the extension thinks it’s yellow:
![image](https://user-images.githubusercontent.com/79421900/188334384-8300a47b-a23b-40da-b1d4-9ce4366a82f5.png)
I’m not sure the cause, as it seems to be a random occurrence. Any ideas? 

It would be so nice to have a function where tst-colorize-tabs reapplies the color to all tabs after a browser restart. I saw in https://github.com/emvaized/tst-colorize-tabs/issues/2 that other extensions might be causing this underlying issue, but I haven’t been able to locate the cause in my config...

**Comment by emvaized** [comment]
Tab colors get stored depending on tab index, e.g. it's number position in the tab list. On each tab create or close, those get updated. What happened in your case, is most likely tab indexes messed up – maybe due to some drag-n-drop reordering? I just figured out the code would not update colors in that case.

> It would be so nice to have a function where tst-colorize-tabs reapplies the color to all tabs after a browser re

No need to, there's [already one](https://github.com/emvaized/tst-colorize-tabs/blob/bc0eec2acc88968162f76cbd982f5f5a13bd7193/background.js#L280) :)

**Comment by kings2u** [comment]
> No need to, there's [already one](https://github.com/emvaized/tst-colorize-tabs/blob/bc0eec2acc88968162f76cbd982f5f5a13bd7193/background.js#L280) :)

Fantastic! Is there a way to call this function on demand, or would that require an update on your end?

**Comment by emvaized** [comment]
It's called automatically on each extension startup. In your case, I think, the problem is not caused by non-working 'colors restore' function, but rather on wrong tab indexes getting stored/restored.

**Comment by kings2u** [comment]
> What happened in your case, is most likely tab indexes messed up – maybe due to some drag-n-drop reordering?

Is there a way to safely reorder tabs without messing with the extension's index? I only know of drag-and-drop, the Tab Mover extension, and a couple functions in Simple Tab Groups and Surfing Keys extensions...

**Comment by emvaized** [comment]
I'm afraid, not — it should be handled by the extension itself.
I just uploaded new version `1.0.2`, which will update stored tab indexes on each tabs reorder. I hope it will solve your issue.

**Comment by emvaized** [comment]
I think this problem shouldn't happen anymore in the new version `2.0.0`. Please feel free to reopen if it does!
