### ISSUE TITLE
Export colored tabs' tree to excel file

### ISSUE THREAD

**Issue by ravirathore** [emvaized/tst-colorize-tabs#6]
Hi,

Thanks for making this extension.

Just wanted to know if its possible to add a functionality to extract the colored tree as an excel file. (As excel file can maintain the tree structure in its cells)

There are libraries like 'sheetjs', that can be used.

Please advise.

thanks,

**Comment by emvaized** [comment]
Hi there! 
I'm not really sure if it's possible to do. But it should be, if you manage to find a way to export TST tabs with all their HTML classes in the tree – and then, process these classes accordingly in the script. 

Tab coloring in this addon is done by adding special classes to the colored tabs (like `self-colored-red`), and corresponding CSS styles to actually colorize them.

**Comment by ravirathore** [comment]
Thanks for the reply.

thanks,
