### ISSUE TITLE
Colours are applied to multiple windows

### ISSUE THREAD

**Issue by ElhemEnohpi** [emvaized/tst-colorize-tabs#7]
Thanks so much for creating this extension! I had something similar years ago that I used all the time, but it stopped working, so I'm looking forwared to having the capability back again. At the moment though, it's not working reliably for me. When I set a colour for a tab in one window, it seems to get set in the other windows too. A least, according to the context menu, and sometimes the actual colours move between windows after a restart.

Steps:

1. Create a new profile and install only TST and TST Colorize Tabs, set to "open previous windows and tabs".
2. Open three new windows, and open two tabs in each.
3. Apply red to the first tab in the third window.

Expected results: only the third window will have red applied to its first tab, and indicated in its "color" submenu.

Actual results: the context menu of the first and second windows also indicate their first tab is red, although visibly they are not.

4. Apply blue to the second tab of the first window.

Expected results: only the first window will have blue applied to its second tab, and indicated in the menu.

Actual results: the second and third windows' menus also indicate their second tab is blue, though visibly they are not.

5. Restart Firefox.

Expected results: The first window's second tab will be blue, the third window's first tab will be red, and the menus will indicate only that.

Actual results: The first window's first tab is now visibly red, and its menu still indicates that. The third window's first tab is no longer visibly red, though its menu indicates it still is, and that its second tab is blue, though it isn't. The second window still has no colours, though its menu still indicates red and blue.

Playing around more with adding or removing colours, and restarting, results in further unexpected and unpredictable behaviours. Removed colours may come back after restarting, colours unable to be removed, adding/removing colours affecting multiple windows, different colours indicated in the menu than are actually visible (as I saw in issue #5) etc. Note I'm not moving or re-ordering any of the tabs at all.

Test environment - all latest versions on Mac:

macOS 13.0
Firefox 106.0.5 and Firefox Developer Edition 107.0b9
Tree Style Tab 3.9.8 
[TST] Colorize tabs 1.0.2

**Comment by emvaized** [comment]
Sorry for long response. 
Yeah, I probably haven't tested the extension that much in multi-window usage. It shouldn't be that hard to add extra checks. 

However, I'm not using this extension anymore, so not sure when I'll be able to look at this. But I'll def. add this on my to do list

**Comment by emvaized** [comment]
This problem should be fixed in the new version `2.0.0` 🚀
